version: '2'
services:
  balancer:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
    - 80:80/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: Balancer=true
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  seed-db:
    image: allhaker/votingapp_backend:development
    environment:
      DATABASE_URL: postgres://votingapp:votingapp@db/votingapp
    links:
    - db:db
    command:
    - node
    - db/seeds.js
    labels:
      io.rancher.container.start_once: 'true'
  backend:
    image: allhaker/votingapp_backend
    environment:
      DATABASE_URL: postgres://votingapp:votingapp@db/votingapp
    links:
    - db:db
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
      service: backend
  frontend:
    image: allhaker/votingapp_frontend
    command:
    - npm
    - run
    - serve
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
      service: frontend
  db:
    image: postgres:9.4
    environment:
      POSTGRES_DB: votingapp
      POSTGRES_PASSWORD: votingapp
      POSTGRES_USER: votingapp
    volumes:
    - /opt/docker/votingapp_data:/var/lib/postgresql/data
    labels:
      io.rancher.scheduler.affinity:host_label: Database=true
